# Use the official Node-RED image as the base
FROM nodered/node-red:4.0-debian

# Switch to the Node-RED user to install additional nodes
USER node-red

# Install additional Node-RED nodes
RUN npm install node-red-contrib-minio-all
RUN npm install node-red-contrib-kafka-manager

# Start Node-RED
CMD ["npm", "start", "--", "--userDir", "/data"]