FROM openwhisk/standalone:6246f6a

RUN apk update && \
    apk add --no-cache wget tar

RUN wget https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz && \
    tar -xzf OpenWhisk_CLI-1.2.0-linux-amd64.tgz && \
    chmod +x wsk && \
    mv wsk /usr/local/bin/ && \
    rm OpenWhisk_CLI-1.2.0-linux-amd64.tgz

# Set environment variables for OpenWhisk
ENV WHISK_HOME=/openwhisk

ENTRYPOINT ["/init"]