# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  # config.vm.synced_folder "./../test", "/test", create: true, id: "vagrant", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=600"]
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 25
  config.ssh.keep_alive = true
  # Prevent Vagrant from inserting its own key in .vagrant/machines/...
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "DIT247"
    vb.gui = false
    vb.memory = "4096" # "2048"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Set PermitRootLogin and PasswordAuthentication if not already set
    # config files might be ssh_config or sth in other linux versions
    if ! grep -q "^PermitRootLogin yes" /etc/ssh/sshd_config; then
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
    fi
    if ! grep -q "^PasswordAuthentication yes" /etc/ssh/sshd_config; then
      echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    fi
    # Restart sshd (maybe ssh or sth in other linux versions)
    # Comment out if "error occurred in the underlying SSH library that Vagrant uses" on >>> vargant provision
    sudo systemctl restart sshd

    # Set root password
    echo "root:root" | sudo chpasswd

    sudo apt-get update && apt-get install -y \
    python3-pip \
    openjdk-8-jdk \
    nodejs \
    npm \
    git \
    curl \
    zip \
    docker.io \
    tar \
    lsof \
    && apt-get clean

    # Download docker compose
    sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

    # Download wsk cli
    sudo curl -L "https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz" -o OpenWhisk_CLI-1.2.0-linux-amd64.tgz
    sudo tar -xzf OpenWhisk_CLI-1.2.0-linux-amd64.tgz
    sudo chmod +x wsk
    sudo mv wsk /usr/local/bin/
    sudo rm OpenWhisk_CLI-1.2.0-linux-amd64.tgz
    sudo rm LICENSE.txt
    sudo rm NOTICE.txt
    
    # Verify installations
    java -version
    docker --version
    docker-compose --version
    wsk --help

    # Download openwhisk
    sudo git clone https://github.com/apache/openwhisk.git

    cd openwhisk

    # Build jar
    sudo ./gradlew --info :core:standalone:build

    # Configure wsk cli
    wsk property set --apihost http://127.0.0.1:3233
    wsk property set --auth `cat ~/openwhisk/ansible/files/auth.guest`

    # Add vagrant user to the docker group
    sudo usermod -aG docker vagrant

    # Remember to share ./../dit247 folder through VirtualBox to /home/vagrant/dit247
    cd /home/vagrant/dit247
  SHELL
end
