version: '3.8'


services:
  srv-kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: ctr-kafka
    ports:
      - ${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}
      - ${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@srv-kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://srv-kafka:${KAFKA_CONTROLLER_PORT},INTERNAL://:${KAFKA_INTERNAL_PORT},EXTERNAL://:${KAFKA_EXTERNAL_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://srv-kafka:${KAFKA_INTERNAL_PORT},EXTERNAL://${KAFKA_EXTERNAL_HOST}:${KAFKA_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # UUID of the Kafka cluster
      CLUSTER_ID: Tnkg34yRTg2PwiiOsoUWLQ
      # Set retention policy to 30 days (720 hours)
      KAFKA_LOG_RETENTION_HOURS: 720
      # Number of topic replicas / must align with the number of broker nodes
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ntw-dit247
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets

  srv-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: ctr-kafka-ui
    restart: always
    ports:
      - ${KAFKAUI_EXTERNAL_PORT}:${KAFKAUI_INTERNAL_PORT}
    depends_on:
      - srv-kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=srv-kafka:${KAFKA_INTERNAL_PORT}
      - KAFKA_CLUSTERS_0_READONLY=false
    networks:
      - ntw-dit247

  srv-nodered:
    build:
      context: .
      dockerfile: Dockerfile.nodered
    container_name: ctr-nodered
    restart: always
    ports:
      - ${NODERD_EXTERNAL_PORT}:${NODERD_INTERNAL_PORT}
    volumes:
      - ./data/nodered:/data
    depends_on:
      - srv-kafka-ui
    networks:
      - ntw-dit247

  srv-minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: ctr-minio
    ports:
      # Console port
      - ${MINIO_EXTERNAL_CONSOLE_PORT}:${MINIO_INTERNAL_CONSOLE_PORT}
      # Web UI port1
      - ${MINIO_EXTERNAL_UI_PORT}:${MINIO_INTERNAL_UI_PORT}
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - ntw-dit247
    depends_on:
      - srv-nodered

  srv-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: ctr-mailhog
    ports:
      # SMTP port
      - ${MAILHOG_EXTERNAL_SMTP_PORT}:${MAILHOG_INTERNAL_SMTP_PORT}
      # Web UI port
      - ${MAILHOG_EXTERNAL_UI_PORT}:${MAILHOG_INTERNAL_UI_PORT}
    networks:
      -  ntw-dit247
    depends_on:
      - srv-minio


volumes:
  kafka-data:
  kafka-secrets:


networks:
  ntw-dit247:
    driver: bridge
